# Generated by Django 3.2.6 on 2021-08-25 09:59

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='Meta Keywords')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Подзаголовок')),
                ('disc', tinymce.models.HTMLField(blank=True, max_length=5000, verbose_name='HTML-Описание')),
                ('slug', models.CharField(help_text='Например tours-online, avia-online и тп', max_length=255, unique=True, verbose_name='Slug')),
                ('news_subjects', models.ManyToManyField(blank=True, related_name='news_subjects', to='news.Stories', verbose_name='Сюжеты')),
            ],
            options={
                'verbose_name': 'Страница партнеров с виджетами',
                'verbose_name_plural': 'Страницы партнеров с виджетами',
            },
        ),
        migrations.CreateModel(
            name='PartnerWidgetScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Название')),
                ('content', models.TextField(blank=True, max_length=5000, verbose_name='HTML-код скрипта')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Сортировка')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.partnerpage')),
            ],
            options={
                'verbose_name': 'Скрипт виджета',
                'verbose_name_plural': 'Скрипты виджета',
                'ordering': ['order'],
            },
        ),
    ]
