# Generated by Django 3.2.6 on 2021-08-25 09:59

import core.mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_visits', models.PositiveIntegerField(default=0, editable=False, verbose_name='Счетчик просмотров')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='страна')),
                ('code', models.CharField(max_length=3)),
                ('slug', models.CharField(db_index=True, max_length=50)),
                ('lang', models.CharField(blank=True, max_length=250, verbose_name='язык')),
                ('last_update_news', models.DateTimeField(blank=True, null=True, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ('title',),
            },
            bases=(core.mixins.VisitsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(verbose_name='Объект')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('like', models.SmallIntegerField(choices=[(-1, '-'), (1, '+')], verbose_name='Нравится/Не нравится')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип объекта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
