# Generated by Django 3.2.6 on 2021-08-25 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.PositiveSmallIntegerField(choices=[(0, 'Сквозной шапка'), (1, 'Сквозной под меню'), (2, 'В левой колонке над новостью'), (3, 'В левой колонке ПОД новостью'), (4, 'В правой колонке на страницах новостей, статей'), (5, 'Список новостей, над 1 новостью '), (6, 'Список новостей, между 5 и 6'), (7, 'Список новостей, между 10 и 11')], db_index=True, default=0, unique=True, verbose_name='Видимость')),
                ('title', models.CharField(help_text='Название для блока виджета', max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(db_index=True, default=False, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Виджет',
                'verbose_name_plural': 'Виджеты',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='WidgetScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Название')),
                ('content', models.TextField(blank=True, max_length=5000, verbose_name='HTML-код скрипта')),
                ('active', models.BooleanField(db_index=True, default=False, verbose_name='Активный')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Сортировка')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banner.widgetregion')),
            ],
            options={
                'verbose_name': 'Скрипт виджета',
                'verbose_name_plural': 'Скрипты виджета',
                'ordering': ['order'],
            },
        ),
    ]
